### ISSUE TITLE
mvn clean install fails due to test fail

### ISSUE THREAD

**Issue by joackobengochea** [neo4j-contrib/spatial-algorithms#1]
Tried to run `mvn clean install` but faild due to a test failure in `algo`

```[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for Spatial Algorithms 0.2.0-neo4j-3.4.14:
[INFO] 
[INFO] Spatial Algorithms ................................. SUCCESS [01:23 min]
[INFO] Spatial Algorithms :: Core ......................... SUCCESS [ 28.304 s]
[INFO] Spatial Algorithms :: Algo ......................... FAILURE [ 10.959 s]
[INFO] Spatial Algorithms :: Neo4j ........................ SKIPPED
[INFO] Spatial Algorithms :: Viewer ....................... SKIPPED
[INFO] Spatial Algorithms :: Benchmarks ................... SKIPPED
[INFO] Spatial Algorithms :: Distribution ................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  02:02 min
[INFO] Finished at: 2019-09-25T12:13:31-03:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.18.1:test (default-test) on project spatial-algorithms-algo: There are test failures.
[ERROR]
 ```

The convexHullNorthPole test fails with the following error: 
```-------------------------------------------------------------------------------
Test set: org.neo4j.spatial.algo.wgs84.WGS84ConvexHullTest
-------------------------------------------------------------------------------
Tests run: 3, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.03 sec <<< FAILURE! - in org.neo4j.spatial.algo.wgs84.WGS84ConvexHullTest
convexHullNorthPole(org.neo4j.spatial.algo.wgs84.WGS84ConvexHullTest)  Time elapsed: 0.015 sec  <<< FAILURE!
java.lang.AssertionError: 
Expected: <InMemorySimplePolygon[InMemoryPoint[0.0, 85.0], InMemoryPoint[90.0, 85.0], InMemoryPoint[180.0, 85.0], InMemoryPoint[-90.0, 85.0], InMemoryPoint[0.0, 85.0]]>
     but: was <InMemorySimplePolygon[InMemoryPoint[-90.0, 85.0], InMemoryPoint[180.0, 85.0], InMemoryPoint[90.0, 90.0], InMemoryPoint[-90.0, 88.0], InMemoryPoint[-90.0, 85.0]]>
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.junit.Assert.assertThat(Assert.java:956)
	at org.junit.Assert.assertThat(Assert.java:923)
	at org.neo4j.spatial.algo.wgs84.WGS84ConvexHullTest.convexHullNorthPole(WGS84ConvexHullTest.java:165)
```

**Comment by craigtaverner** [comment]
I have fixed this during some recent work. Please try the latest.

**Comment by joackobengochea** [comment]
Thanks!
